#Whilst the Werewolf specific Ageing options are here, the general configuration options are in the main vampiricAgeing config. For example, resetting age on death or the level to begin ageing is managed in the main config, not this one
#Whenever there is a list with 6 values you can change, the first value refers to a player with Age 0 Rank. The final value therefore refers to an Age 5 Player
#Whether Werewolves can Age. Requires Werewolves Addon for Vampirism.
werewolfAgeing = true
#The level at which the age mechanic begins
# Default: 14
# Range: 0 ~ 14
levelToBeginAgeMechanic = 14
#Change to select Ageing type. Valid Options include: DEVOUR
ageingMethod = "DEVOUR"
#How many points worth of devoured entities are needed to increase Age Rank. Count is reset on Rank Up
devouredforNextAge = [30, 60, 100, 250, 500]
#How much a petty devour is worth. These are things like basic animals
# Default: 1
# Range: 0 ~ 99
pettyDevourWorth = 1
#How much a common devour is worth. These are things like certain hostile mobs
# Default: 2
# Range: 0 ~ 99
commonDevourWorth = 2
#How much a greater devour is worth. These are things like advanced faction mobs
# Default: 5
# Range: 0 ~ 99
greaterDevourWorth = 5
#How much a exquisite devour is worth. These are things like vampire barons
# Default: 10
# Range: 0 ~ 99
exquisiteDevourWorth = 10
#Max Health Increase for each rank. This is addition, not multiplier based
maxHealthIncrease = [0.0, 2.0, 2.0, 4.0, 4.0, 6.0]
#How much each rank multiplies bite damage. Bite damage multiplier is strange and values of 0 should be treated as 1, values like 0.2 should be treated as a 1.2 multiplier
biteDamageMultiplier = [0.0, 0.0, 0.0, 0.125, 0.25, 0.5]
#How much each rank multiplies damages from Silver Oil. Values are set to 1 by default as to disable it by default.
silverOilMultiplier = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
#How much the player is healed for biting an entity based on rank
healonBiteAmount = [0.0, 0.0, 0.0, 1.0, 2.0, 2.0]
#How much the duration of time a player can stay in werewolf form is multiplied by
formTimeMultiplier = [1.0, 1.5, 2.0, 3.0, 4.0, 5.0]
#Whether higher age ranks buffs the mobs summoned by howling
ageBuffsHowl = true
#When enabled, biting an entity provides sustenance
bitingGivesFood = true
#Requires bitingGivesFood to be enabled. At what rank should biting begin to give food
# Default: 2
# Range: 0 ~ 5
rankForBitefood = 2
#How much nutrition (hungar bar value) a bite gives
# Default: 1
# Range: 0 ~ 20
biteNutrition = 1
#How much saturation a bite gives
# Default: 0.1
# Range: 0.0 ~ 1.2
biteSaturation = 0.1
#How much more nourishing raw meat is for a werewolf based on age rank
nourishmentMultipliers = [1, 1, 2, 2, 3, 3]
#How much each age rank increases damage by adding on to base damage. Set all to 0 to disable completely.
ageDamageIncrease = [0.0, 0.0, 1.0, 2.0, 3.0, 4.0]
