[common_server]
	#Only considered if terrablender installed. Heigher values increase Werewolf region weight (likelyhood to appear)
	# Default: 2
	# Range: 1 ~ 1000
	werewolfBiomeWeightTerrablender = 2
	#Disable werewolf forest generation
	disableWerewolfForest = false
	#Weight of silver ore spawning
	# Default: 30
	# Range: 0 ~ 256
	silverOreWeight = 30
